"""
ConstructedAnswer data model — Epic 11, Story 01.

Defines the rich retrieval payload that replaces the flat MemoryFact list.
A ConstructedAnswer separates directly retrieved facts from derived inferences
and explicitly marks knowledge gaps, giving callers full transparency into
the quality and completeness of the reconstructed answer.

Bio mapping:
- ConstructedFact (source='direct')        → exact engram reactivation: stored trace retrieved
- ConstructedFact (source='reconstructed') → partial cue completion: engram partially matches
- Inference                                → neocortical semantic generalisation: derived from
                                             pattern stored across multiple engrams
- Gap                                      → CA1 mismatch signal: expected information not found
- overall_confidence                       → ensemble plasticity weight for the reconstruction
- mode_influence                           → current neuromodulatory state biases construction

Concept reference: docs/engram/concept.md — Chapter 11 (Constructive Memory)
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from ..response_models import MemoryFact


# ---------------------------------------------------------------------------
# T1 — ConstructedFact
# ---------------------------------------------------------------------------


class ConstructedFact(BaseModel):
    """
    A single fact included in a ConstructedAnswer.

    Wraps a retrieved Engram with its confidence and provenance.

    Attributes:
        engram_id:       ID of the source Engram in the memory store.
        content:         The fact text (may be lightly reformatted for context).
        confidence:      0.0–1.0 combined retrieval score (lower for weak-link traversal).
        source:          'direct'       — Engram retrieved unmodified.
                         'reconstructed'— Content adapted to fit query context.
        tags:            Tags from the source Engram (propagated for filtering).
        thalamus_scores: Raw Thalamus component scores (novelty, surprise, etc.) if available.
    """

    engram_id: str = Field(description="Source Engram ID")
    content: str = Field(description="Fact text content")
    confidence: float = Field(ge=0.0, le=1.0, description="Retrieval confidence (combined score)")
    source: Literal["direct", "reconstructed"] = Field(
        description="'direct' = unmodified Engram; 'reconstructed' = adapted to context"
    )
    tags: list[str] = Field(default_factory=list, description="Tags from source Engram")
    thalamus_scores: dict[str, float] = Field(
        default_factory=dict,
        description="Raw Thalamus component scores (novelty, surprise, task_relevance, emotional_valence)",
    )


# ---------------------------------------------------------------------------
# T2 — Inference
# ---------------------------------------------------------------------------


class Inference(BaseModel):
    """
    A derived conclusion — not explicitly stored, but implied by retrieved facts.

    Generated by the LLM during the Inference Phase of the Construction Pipeline.

    Attributes:
        content:               The inferred statement text.
        confidence:            0.0–1.0 LLM confidence in the inference.
        supporting_engram_ids: IDs of Engrams that support this inference.
        inference_type:        How the inference was derived.
        reasoning:             Explanation of the reasoning step (transparency).
    """

    content: str = Field(description="The inferred statement")
    confidence: float = Field(ge=0.0, le=1.0, description="LLM confidence in the inference")
    supporting_engram_ids: list[str] = Field(
        default_factory=list,
        description="Engram IDs that support this inference",
    )
    inference_type: Literal["deduction", "analogy", "interpolation", "extrapolation"] = Field(
        description=(
            "deduction=logical necessity, analogy=cross-domain similarity, "
            "interpolation=filling between known points, extrapolation=extending beyond known data"
        )
    )
    reasoning: str = Field(description="Brief explanation of the reasoning step")


# ---------------------------------------------------------------------------
# T3 — Gap
# ---------------------------------------------------------------------------


class Gap(BaseModel):
    """
    An identified knowledge gap — information expected but not found.

    Generated by the LLM during the Gap Detection Phase.

    Attributes:
        description:        What information is missing.
        relevance:          0.0–1.0 how important this gap is for the query.
        related_engram_ids: Engrams whose content is adjacent to the gap.
        suggested_query:    How to fill the gap (next search query or action).
    """

    description: str = Field(description="Description of the missing information")
    relevance: float = Field(ge=0.0, le=1.0, description="Importance of this gap for the query")
    related_engram_ids: list[str] = Field(
        default_factory=list,
        description="Engrams adjacent to the gap (partial context)",
    )
    suggested_query: str | None = Field(
        None,
        description="Suggested follow-up query to fill this gap",
    )


# ---------------------------------------------------------------------------
# T4 — ConstructedAnswer
# ---------------------------------------------------------------------------


class ConstructedAnswer(BaseModel):
    """
    A fully constructed answer assembling facts, inferences, and gaps.

    The primary output of the Construction Pipeline. Replaces the flat
    MemoryFact list when a Session is active.

    Attributes:
        facts:                  Directly retrieved or reconstructed Engram facts.
        inferences:             LLM-derived conclusions from the facts.
        gaps:                   Identified knowledge gaps.
        overall_confidence:     Weighted mean of fact confidences × coverage factor.
        mode_influence:         Which construction_style was active (e.g. 'conservative').
        construction_metadata:  Timing, LLM tier used, raw counts, etc.
    """

    facts: list[ConstructedFact] = Field(default_factory=list)
    inferences: list[Inference] = Field(default_factory=list)
    gaps: list[Gap] = Field(default_factory=list)
    overall_confidence: float = Field(
        ge=0.0, le=1.0, default=0.0, description="Aggregate confidence across facts and gaps"
    )
    mode_influence: str = Field(
        default="conservative",
        description="construction_style active during this construction cycle",
    )
    construction_metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Pipeline metadata: timing, LLM tier, raw counts, prediction_error info",
    )

    def to_memory_facts(self) -> list[MemoryFact]:
        """
        Degrade to a flat list of MemoryFact for backward compatibility.

        Returns one MemoryFact per ConstructedFact, ignoring inferences and gaps.
        Callers that don't know about ConstructedAnswer can use this to stay compatible.
        """
        from ..response_models import MemoryFact

        return [
            MemoryFact(
                id=fact.engram_id,
                text=fact.content,
                fact_type="general",
                metadata={"confidence": str(round(fact.confidence, 4)), "source": fact.source},
            )
            for fact in self.facts
        ]

    @property
    def has_gaps(self) -> bool:
        """True if any significant gaps (relevance ≥ 0.3) were detected."""
        return any(g.relevance >= 0.3 for g in self.gaps)

    @property
    def fact_count(self) -> int:
        return len(self.facts)

    @property
    def inference_count(self) -> int:
        return len(self.inferences)
